### ISSUE TITLE
que projeto fantástico

### ISSUE THREAD

**Issue by ghost** [Dev-ES/awesome-finance#5]
Oi pessoal, quero muito ajudar! estão dispostos a ouvir minhas ideias?

**Comment by jvrmaia** [comment]
não estamos mais mantendo esse projeto mas se quiser mandar qualquer contribuição, pode ficar a vontade

**Comment by ghost** [comment]
Oi @jvrmaia, tudo bem. mas se eu enviar um pull-request você aceitaria? fiz um pull-request aqui: [add nanda guardian](https://github.com/Dev-ES/awesome-finance/pull/6)

**edit** @jvrmaia obrigado por aceitar o pull-request, vou fechar essa issue aqui. tenha um bom dia.
